apiVersion: v2
appVersion: 1.13.0
description: A Helm chart for deploying the Percona Operator for MongoDB
home: https://docs.percona.com/percona-operator-for-mongodb/
maintainers:
- email: ivan.pylypenko@percona.com
  name: cap1984
- email: tomislav.plavcic@percona.com
  name: tplavcic
- email: sergey.pronin@percona.com
  name: spron-in
name: psmdb-operator
version: 1.13.2
